[colors.bright]
black = "#545753"
blue = "#156ffe"
cyan = "#39d5ce"
green = "#2cc631"
magenta = "#e800b0"
red = "#fb0416"
white = "#ededec"
yellow = "#fcd627"

[colors.cursor]
cursor = "#6fd2fc"

[colors.normal]
black = "#000000"
blue = "#125ccf"
cyan = "#32c2c0"
green = "#32895c"
magenta = "#9f00bc"
red = "#f72729"
white = "#b2b2b2"
yellow = "#f96f1c"

[colors.primary]
background = "#ffffff"
foreground = "#262626"

[colors.selection]
background = "#6fd2fc"
text = "#ffffff"
