[colors.bright]
black = "#404040"
blue = "#A6A6A6"
cyan = "#A6A6A6"
green = "#D9D9D9"
magenta = "#A6A6A6"
red = "#D9D9D9"
white = "#D9D9D9"
yellow = "#595959"

[colors.cursor]
cursor = "#A6A6A6"
text = "#D9D9D9"

[colors.normal]
black = "#404040"
blue = "#A6A6A6"
cyan = "#A6A6A6"
green = "#D9D9D9"
magenta = "#A6A6A6"
red = "#D9D9D9"
white = "#D9D9D9"
yellow = "#595959"

[colors.primary]
background = "#262626"
foreground = "#D9D9D9"

[colors.selection]
background = "#A6A6A6"
text = "#262626"
