
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# exec-once = systemctl --user start graphical-session.target # for Gammastep
# exec-once = gammastep
# exec-once = hypridle

# Keybinds
unbind  = , F10
unbind = , F11
unbind = , F12

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    # kb_layout = us
    # follow_mouse = 1
    # sensitivity = 0
    # force_no_accel = 0
    # accel_profile = flat 
    # numlock_by_default = true
    kb_options = compose:ralt

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        # natural_scroll = no
    }

}



# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}

# for window shallow similar to devour
misc {
    # enable_swallow = true
    # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  # no_update_news = true
}


