# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml
[hyprland]
terminal = "alacritty"

[waybar]
position = "bottom"

[weather]
location = "DOU_BR"
temperature_unit = "c"
